GET {{host}}/lancamento/get/19
Accept: application/json

###
POST http://localhost:8080/contabil/lancamento/adicionar
Content-Type: application/json

{
  "codigoUsuario": 46,
  "data": "2020-06-08T00:00:00",
  "historico": "Lançamento teste do usuário paulo",
  "valores": [
    {
      "tipo": "DEBITO",
      "codigoConta": 272,
      "data": "2020-06-08T00:00:00",
      "historico": "Lançamento teste do usuário paulo",
      "valor": 100.00
    },
    {
      "tipo": "CREDITO",
      "codigoConta": 266,
      "data": "2020-06-08T00:00:00",
      "historico": "Lançamento teste do usuário paulo",
      "valor": 100.00
    }
  ]
}

###


