POST http://127.0.0.1:8080/contabil/conta/adicionar
Content-Type: application/json

{
  "contaPaiCodigo": 3,
  "codigoUsuario": 8,
  "nome": "Teste",
  "saldo": 0
}


###
POST http://127.0.0.1:8080/contabil/conta/adicionar
Content-Type: application/json

{
  "contaPaiCodigo": 7,
  "codigoUsuario": 8,
  "nome": "Bancos",
  "saldo": 0
}
###
POST http://127.0.0.1:8080/contabil/conta/adicionar
Content-Type: application/json

{
  "contaPaiCodigo": 7,
  "codigoUsuario": 8,
  "nome": "Caixa",
  "saldo": 0
}

###
POST http://127.0.0.1:8080/contabil/conta/adicionar
Content-Type: application/json

{
  "contaPaiCodigo": 6,
  "codigoUsuario": 8,
  "nome": "Imediato",
  "saldo": 0
}

###
POST http://127.0.0.1:8080/contabil/conta/adicionar
Content-Type: application/json

{
  "contaPaiCodigo": 1,
  "codigoUsuario": 8,
  "nome": "Disponível",
  "saldo": 0
}

###
